version: "3.9"

name: DACP

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: dacp
    volumes:
      - ./data/mongo-data:/data/db
    ports:
      - "27017:27017"